### ISSUE TITLE
Basic support for impure dependencies

### ISSUE THREAD

**Issue by weberc2** [weberc2/gubernator#1]
At some point, the headache of packaging certain dependencies exceeds the headache of ensuring certain system dependencies are set up properly. For those use cases, we should allow developers to use "impure" system dependencies. In other words, developers should be able to say "I don't want to write the build definition for this dependency; just use the system version and I'll take responsibility for making sure other developers have it installed properly".

This doesn't actually require changes to g8r to support this use case in some basic fashion. Effectively, developers will implement this pattern:

* There is a .impure directory inside of the workspace which contains symlinks to system dependencies
* Because these symlinks are system dependencies which will vary across developers' machines, there should be a .gitignore entry hiding them: `.impure/*`
* Each developer on the project will be responsible for setting up their own symlinks (for convenience, the repo owner can provide a bootstrap script that installs these dependencies and symlinks from brew, nix, etc)
* These symlinks will be individually referenced by the toplevel `.star` files by `path()` or `glob()` builtin functions as appropriate, at which point they will be treated by g8r as ordinary files in the repository (frozen into the cache; the hash of these files will be incorporated into the hash of anything that depends on them downstream).
    * From here they can be used as though they were built by g8r directly, typically by passing these into starlark functions that take dependencies and return a dependent target
* In addition to straightforward globbing, they may be wrapped in a target that smoke-tests them (checks their version and feature set) before passing them onto other functions

To use g8r as an example, g8r is a Go project with a `modules/go/default.star` file that defines Go target functions including `build` and `test`. These target functions take a `goTool` target dependency which they use to build their target artifact. Until we figure out how to package the `goTool` reproducibly, this is an impure dependency. Users will need to install Go and symlink it to .impure/go. The toplevel `default.star` file will reference it via `path(".impure/go")` and wrap it in a target that tests it. The result will be passed into a `build(goTool=<gotool-target-variable>, ...)` and `test(goTool=<gotool-target-variable>)`.

## Tasks
- [ ] Documentation for impure dependencies, describing the above
- [x] Implement the above pattern for the impure GOTOOL dependency in the g8r default.star file
    - [x] Freezing targets should factor in the file bits such that a frozen executable is runnable from cache (similarly, two otherwise-identical files with different bits should hash differently). This blocks the above GOTOOL example because presently freezing the GOTOOL symlink doesn't preserve its bit set.
